# Generated by Django 4.0.3 on 2022-04-10 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0002_alter_market_market_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='market_end_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='market',
            name='market_start_time',
            field=models.TimeField(null=True),
        ),
    ]
