# Generated by Django 4.0.3 on 2022-04-10 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0003_alter_market_market_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='stock_ticker',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
