# Generated by Django 4.0.3 on 2022-04-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0004_stock_stock_ticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='volumes',
            field=models.FloatField(null=True),
        ),
    ]
