# Generated by Django 4.0.3 on 2022-04-10 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0005_stock_volumes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_created_dt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
