# Generated by Django 4.0.3 on 2022-04-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0006_alter_stock_stock_created_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='stock_created_dt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
