# Generated by Django 4.0.3 on 2022-04-13 23:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0007_alter_stock_stock_created_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_available', models.FloatField(null=True)),
                ('user_withdrawal_limit', models.FloatField(default=500, null=True)),
                ('user_deposit_limit', models.FloatField(default=500, null=True)),
                ('withdraw_date', models.DateTimeField(null=True)),
                ('deposit_date', models.DateTimeField(null=True)),
                ('user_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='stockmarket.userinfo')),
            ],
        ),
    ]
