# Generated by Django 4.0.3 on 2022-04-14 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0008_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='stock_cash',
            field=models.FloatField(default=0, null=True),
        ),
    ]
