# Generated by Django 4.0.3 on 2022-04-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0009_bank_stock_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='limit_order_date',
            field=models.DateTimeField(null=True),
        ),
    ]
