# Generated by Django 4.0.3 on 2022-04-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0012_limitorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='limitorders',
            name='stock_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
