# Generated by Django 4.0.3 on 2022-04-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0013_alter_limitorders_stock_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='limitorders',
            old_name='limitOrder_time',
            new_name='expiration_dt',
        ),
        migrations.AddField(
            model_name='limitorders',
            name='limitOrder_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='limitorders',
            name='limitOrder_volumes',
            field=models.FloatField(null=True),
        ),
    ]
