# Generated by Django 4.0.3 on 2022-04-15 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0015_transactionhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='limitorders',
            name='created_dt',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
