# Generated by Django 4.0.3 on 2022-04-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockmarket', '0016_limitorders_created_dt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day_trade',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
